# Generated by Django 6.0.2 on 2026-03-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_claim_alter_entry_id_alter_topic_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='policy_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='claim',
            name='vin',
            field=models.CharField(default='', max_length=100),
        ),
    ]
