# Generated by Django 6.0.2 on 2026-03-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_claim_policy_number_claim_vin'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='claims/'),
        ),
    ]
