# Generated by Django 6.0.2 on 2026-03-27 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('claim_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('claim_level', models.CharField(blank=True, choices=[('LOW', 'Under 1500'), ('HIGH', '1500+')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('MORE_INFO', 'More Info Required')], default='PENDING', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('policy_number', models.CharField(default='', max_length=100)),
                ('vin', models.CharField(default='', max_length=100)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='claims/')),
            ],
        ),
        migrations.CreateModel(
            name='Dealership',
            fields=[
                ('dealershipid', models.IntegerField(db_column='dealershipID', primary_key=True, serialize=False)),
                ('address', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('phonenumber', models.TextField(blank=True, db_column='phoneNumber', null=True)),
            ],
            options={
                'db_table': 'Dealership',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('partid', models.IntegerField(db_column='partID', primary_key=True, serialize=False)),
                ('partname', models.TextField(blank=True, db_column='partName', null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('cost', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Inventory',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerid', models.TextField(db_column='customerID', primary_key=True, serialize=False)),
                ('firstname', models.TextField(blank=True, db_column='firstName', null=True)),
                ('lastname', models.TextField(blank=True, db_column='lastName', null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('dealershipid', models.ForeignKey(blank=True, db_column='dealershipID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='learning_logs.dealership')),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_logs.topic')),
            ],
            options={
                'verbose_name_plural': 'Entries',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicleid', models.IntegerField(db_column='vehicleID', primary_key=True, serialize=False)),
                ('model', models.TextField(max_length=100)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('mileage', models.IntegerField(blank=True, null=True)),
                ('vin', models.CharField(blank=True, db_column='VIN', max_length=50, null=True)),
                ('customerid', models.ForeignKey(blank=True, db_column='customerID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='learning_logs.customer')),
            ],
            options={
                'db_table': 'Vehicle',
            },
        ),
        migrations.CreateModel(
            name='Warrantypolicy',
            fields=[
                ('policyid', models.IntegerField(db_column='policyID', primary_key=True, serialize=False)),
                ('startdate', models.DateField(blank=True, db_column='startDate', null=True)),
                ('enddate', models.DateField(blank=True, db_column='endDate', null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('coveragetype', models.TextField(blank=True, db_column='coverageType', null=True)),
                ('vehicleid', models.ForeignKey(blank=True, db_column='vehicleID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='learning_logs.vehicle')),
            ],
            options={
                'db_table': 'WarrantyPolicy',
            },
        ),
    ]
