# Generated by Django 5.2.12 on 2026-03-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_logs", "0002_topic_owner_alter_entry_id_alter_topic_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "customerid",
                    models.TextField(
                        db_column="customerID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "firstname",
                    models.TextField(blank=True, db_column="firstName", null=True),
                ),
                (
                    "lastname",
                    models.TextField(blank=True, db_column="lastName", null=True),
                ),
                ("phone", models.TextField(blank=True, null=True)),
                ("email", models.TextField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "Customer",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Dealership",
            fields=[
                (
                    "dealershipid",
                    models.IntegerField(
                        db_column="dealershipID", primary_key=True, serialize=False
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("name", models.TextField(blank=True, null=True)),
                (
                    "phonenumber",
                    models.TextField(blank=True, db_column="phoneNumber", null=True),
                ),
            ],
            options={
                "db_table": "Dealership",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "vehicleid",
                    models.IntegerField(
                        db_column="vehicleID", primary_key=True, serialize=False
                    ),
                ),
                ("model", models.TextField(blank=True, null=True)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("mileage", models.TextField(blank=True, null=True)),
                ("vin", models.IntegerField(blank=True, db_column="VIN", null=True)),
            ],
            options={
                "db_table": "Vehicle",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Warrantypolicy",
            fields=[
                (
                    "policyid",
                    models.IntegerField(
                        db_column="policyID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "startdate",
                    models.TextField(blank=True, db_column="startDate", null=True),
                ),
                (
                    "enddate",
                    models.FloatField(blank=True, db_column="endDate", null=True),
                ),
                ("status", models.TextField(blank=True, null=True)),
                (
                    "coveragetype",
                    models.TextField(blank=True, db_column="coverageType", null=True),
                ),
            ],
            options={
                "db_table": "WarrantyPolicy",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=100)),
                ("sku", models.CharField(max_length=50, unique=True)),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("reorder_level", models.PositiveIntegerField(default=5)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
