# Generated by Django 6.0.3 on 2026-03-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_customer_dealership_vehicle_warrantypolicy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('partid', models.IntegerField(db_column='partID', primary_key=True, serialize=False)),
                ('partname', models.TextField(blank=True, db_column='partName', null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('cost', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Inventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('claim_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('claim_level', models.CharField(blank=True, choices=[('LOW', 'Under 1500'), ('HIGH', '1500+')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('MORE_INFO', 'More Info Required')], default='PENDING', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('policy_number', models.CharField(default='', max_length=100)),
                ('vin', models.CharField(default='', max_length=100)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='claims/')),
            ],
        ),
        migrations.DeleteModel(
            name='InventoryItem',
        ),
        migrations.AlterField(
            model_name='entry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
