# Generated by Django 5.2.12 on 2026-03-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "learning_logs",
            "0004_inventory_claim_delete_inventoryitem_alter_entry_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="claim",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="entry",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
