# Generated by Django 5.2.12 on 2026-04-02 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_logs", "0005_alter_claim_id_alter_entry_id_alter_topic_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClaimRecord",
            fields=[
                (
                    "claimid",
                    models.IntegerField(
                        db_column="claimID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "vehicleid",
                    models.IntegerField(blank=True, db_column="vehicleID", null=True),
                ),
                (
                    "claimstatus",
                    models.TextField(blank=True, db_column="claimStatus", null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "claimamount",
                    models.FloatField(blank=True, db_column="claimAmount", null=True),
                ),
                (
                    "claimdate",
                    models.TextField(blank=True, db_column="claimDate", null=True),
                ),
            ],
            options={
                "db_table": "Claim",
                "managed": False,
            },
        ),
        migrations.AlterField(
            model_name="claim",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="claim",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Denied", "Denied"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="entry",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
